spring:
  application:
    name: "kafka-benchmark-producer"
  jmx:
    enabled: true
bootstrap.servers: "localhost:9092"
admin.timeout.ms: 6000
wait.consumers.delay.ms: 2000
server:
  port: ${PORT}
management:
  port: ${PORT}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
