spring:
  application:
    name: "kafka-benchmark-runner"
  jmx:
    enabled: true
bootstrap.servers: "localhost:9092"
admin.timeout.ms: 6000
admin.topic: _benchmark
server:
  port: ${PORT}
management:
  port: ${PORT}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
